### PR TITLE
Bugfix/cursor select line

### PR DESCRIPTION
**Pull request by aaxu**
This should fix cursorSelectLine, clicking line numbers, and not break #109 .

### CODE REVIEW

**Comment by aaxu** [comment]
Should close #122

**Comment by aaxu** [comment]
I don't know if it's just me, but shift clicking doesn't seem to be working for anything, even if I'm on the master branch.

**Comment by dschuyler** [comment]
Shift clicking:

It's not working for me either.

**Comment by aaxu** [comment]
I've gone back several months back worth of commits and it didn't seem to be working either. Do we know if it's detectable by the program? It looks like it might be intercepted by the terminal as a way to "select" over any program.

**Comment by dschuyler** [comment]
There's a behavior I was trying to mimc in the line selection. Imagine clicking on line number for line 2 in the example and then dragging into the document area onto the 'm'.
```
  1 cat
  2 dog
  3 hamster
```
The selection should stop at the 'm' rather than going to the 'r'. The PR appears to have the extension go to the 'r'.

(I'm also up for discussing whether this is good or not. I think it was the thing I was fixing when I broke the ctrl+L line selection).

**Comment by dschuyler** [comment]
On shift clicking: it works in Mac OSX, but didn't work for me on Ubuntu.

**Comment by aaxu** [comment]
I actually don't see it going to the 'r'. For me, when I drag my mouse to the 'm', nothing happens and the selection does not change unless my mouse goes to the line after (so the invisible line 4 in this case).

**Pull request merged**
