### PR TITLE
Fix IndexError on mutator.py

### LINKED ISSUE #22: 'm' index error
Not sure of full repro steps. I need to follow up on this.

info text_buffer.py 842 mouseRelease:  mouse release 10 0
detail mutator.py 355 undoOne: undo
detail mutator.py 409 undoOne: undo move
error ci_program.py 534 wrapped_ci: Traceback (most recent call last):
error ci_program.py 534 wrapped_ci:   File "/usr/local/google/home/dschuyler/github/ci_edit/app/ci_program.py", line 529, in wrapped_ci
    prg.run()
error ci_program.py 534 wrapped_ci:   File "/usr/local/google/home/dschuyler/github/ci_edit/app/ci_program.py", line 502, in run
    self.commandLoop()
error ci_program.py 534 wrapped_ci:   File "/usr/local/google/home/dschuyler/github/ci_edit/app/ci_program.py", line 97, in commandLoop
    self.refresh()
error ci_program.py 534 wrapped_ci:   File "/usr/local/google/home/dschuyler/github/ci_edit/app/ci_program.py", line 466, in refresh
    k.refresh()
error ci_program.py 534 wrapped_ci:   File "/usr/local/google/home/dschuyler/github/ci_edit/app/window.py", line 767, in refresh
    self.topInfo.onChange()
error ci_program.py 534 wrapped_ci:   File "/usr/local/google/home/dschuyler/github/ci_edit/app/window.py", line 555, in onChange
    if tb.isDirty():
error ci_program.py 534 wrapped_ci:   File "/usr/local/google/home/dschuyler/github/ci_edit/app/mutator.py", line 99, in isDirty
    self.redoChain[self.redoIndex][0] == 'm') or
error ci_program.py 534 wrapped_ci: IndexError: list index out of range

### PR DESCRIPTION
**Pull request by stasfilin**
Resolve #22

### CODE REVIEW

**Comment by dschuyler** [comment]
Great, thanks. Hey did you find repro steps for #22?

**Comment by stasfilin** [comment]
@dschuyler I just mocked class for getting this error, but I can investigate.
Did you remember what did you do when you got this error?

**Comment by dschuyler** [comment]
I'm not sure, so I added a block of asserts just before where this failure happens.

I'd been editing for awhile. So there were some copies, pastes, moving around, and saving. My concern is that there may be something amiss with the tempChange, redoChain, or related indexes.

**Comment by stasfilin** [comment]
@dschuyler okay, I check this,
on this Pull Request? Or we close this and create the new one?
Also, I want to create a new issue for to write the information that I found for this error

**Comment by dschuyler** [comment]
Sorry I've been slow to respond this week. I'll try to look at PRs on Friday.

**Comment by dschuyler** [comment]
Thanks stasfilin for this PR. It really helped me work out what was up. I ended up making a different (though similar) change to address the issue. So even though I'm not landing this PR directly, I wanted to thank you for leading me to the answer.

**Pull request closed without merging**
