### PR TITLE
Added a way to run ci_edit directly on an online compiler, Repl.it

### PR DESCRIPTION
**Pull request by nraikm**
I have added a one click button, which will automatically set up ci_edit and run the editor in the Repl.it online environment.
image

### CODE REVIEW

**Comment by dschuyler** [comment]
Thanks. Hey, when I looked at ci_edit on replit, the cursor doesn't show up (it looks like it's white on a white background). Does it look that way for you?

**Comment by Mosrod** [comment]
Yeah, it looks the same for me, and I believe it is due to the cursor being on a white background (as you have explained above).

**Comment by dschuyler** [comment]
I like the idea of this PR. It gives potential users a chance to see (and use) ci_edit. With the white cursor, I'm concerned that someone would pass on using ci_edit. That would be sad.

Do you have time to look into the issue and see if we can get the cursor to show up (before we land this PR)?

**Comment by Mosrod** [comment]
Repl.it uses a white cursor on the terminal, and I couldn't figure out a way to change it. I believe that changing the cursor would require changes to their environment, but there might be another way to do it. Perhaps in the future, there might be more console themes, which would change the cursor to the desired color. I agree that some people might pass on using ci_edit due to the white cursor, and maybe I could add a notice that would tell people that the cursor is white.

**Pull request closed without merging**
